name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  intl: ^0.18.0
  get_storage: ^2.0.3
  cached_network_image: ^3.2.1
  file_picker: ^5.2.6
  package_info_plus: ^3.0.3
  pinput: ^2.2.31
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  url_launcher: ^6.1.10

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/icons/
    - assets/locales/
    - assets/logo/