name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  intl: ^0.18.0
  get_storage: ^2.0.3
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  file_picker: ^5.2.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/icons/
    - assets/locales/